In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import missingno as msno

irradiance = pd.read_csv("data/irradiance_anonymized.csv")
pv_data = pd.read_csv("data/pv_data.csv", sep=";")
weather = pd.read_csv("data/weather.csv")

In [30]:
irradiance["dt"] = pd.to_datetime(irradiance["dt"])
pv_data["timestamp"] = pd.to_datetime(pv_data["timestamp"])
weather["time"] = pd.to_datetime(weather["time"])

In [31]:
def missing_report(df):
    return pd.DataFrame({
        "Missing Values": df.isna().sum(),
        "Percentage": df.isna().mean() * 100
    }).sort_values("Percentage", ascending=False)

## Missing Values

### Strahlung

In [32]:
missing_report(irradiance)

                Missing Values  Percentage
dt                           0         0.0
dt_iso                       0         0.0
timezone                     0         0.0
city_name                    0         0.0
lat                          0         0.0
lon                          0         0.0
ghi_cloudy_sky               0         0.0
dni_cloudy_sky               0         0.0
dhi_cloudy_sky               0         0.0
ghi_clear_sky                0         0.0
dni_clear_sky                0         0.0
dhi_clear_sky                0         0.0

In [33]:
irradiance.describe()

,dt,timezone,lat,lon,ghi_cloudy_sky,dni_cloudy_sky,dhi_cloudy_sky,ghi_clear_sky,dni_clear_sky,dhi_clear_sky
count,117640,117640.000000,117640.0,117640.0,117640.000000,117640.000000,117640.000000,117640.000000,117640.000000,117640.000000
mean,1970-01-01 00:00:01.697179950,5723.889833,0.0,0.0,43.939214,60.188641,12.502226,50.171778,82.684919,10.019393
min,1970-01-01 00:00:01.644242400,3600.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1970-01-01 00:00:01.670711175,3600.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1970-01-01 00:00:01.697179950,7200.000000,0.0,0.0,0.970000,0.000000,0.970000,1.350000,12.550000,2.900000
75%,1970-01-01 00:00:01.723648725,7200.000000,0.0,0.0,73.690000,142.622500,21.030000,91.370000,179.180000,20.960000
max,1970-01-01 00:00:01.750117500,7200.000000,0.0,0.0,228.440000,230.190000,107.910000,228.440000,226.670000,29.930000
std,NaN,1770.627580,0.0,0.0,63.863072,82.428209,17.722318,68.577525,90.642364,11.130158

### PV Data

In [34]:
missing_report(pv_data)

                                   Missing Values  Percentage
Wallbox (ID 0) Gesamtladeleistung           21308   18.708295
Wallbox (ID 0) Netzbezug                    21308   18.708295
Wallbox (ID 0) Solarladeleistung            21308   18.708295
Wallbox Gesamtladeleistung                  21308   18.708295
timestamp                                       0    0.000000
Ladezustand                                     0    0.000000
Batterie (Laden)                                0    0.000000
Batterie (Entladen)                             0    0.000000
Netzeinspeisung                                 0    0.000000
Netzbezug                                       0    0.000000
Solarproduktion Tracker 1                       0    0.000000
Solarproduktion Tracker 2                       0    0.000000
Solarproduktion Tracker 3                       0    0.000000
Solarproduktion                                 0    0.000000
Hausverbrauch                                   0    0.000000
Σ Verbrauch                                     0    0.000000

In [35]:
pv_data.describe()

,timestamp,Ladezustand,Batterie (Laden),Batterie (Entladen),Netzeinspeisung,Netzbezug,Solarproduktion Tracker 1,Solarproduktion Tracker 2,Solarproduktion Tracker 3,Solarproduktion,Hausverbrauch,Wallbox (ID 0) Gesamtladeleistung,Wallbox (ID 0) Netzbezug,Wallbox (ID 0) Solarladeleistung,Wallbox Gesamtladeleistung,Σ Verbrauch
count,113896,113896.000000,113896.000000,113896.000000,113896.000000,113896.000000,113896.000000,113896.000000,113896.0,113896.000000,113896.000000,92588.000000,92588.000000,92588.000000,92588.000000,113896.000000
mean,2023-10-13 14:52:59.332022272,56.367985,85.004662,83.197399,159.446091,38.802829,113.128389,214.986268,0.0,328.114657,158.253082,34.312384,11.865739,22.446645,34.312384,186.146204
min,2022-02-07 14:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000
25%,2022-12-11 04:26:15,20.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.0,0.000000,81.000000,0.000000,0.000000,0.000000,0.000000,81.000000
50%,2023-10-13 18:52:30,62.000000,0.000000,12.000000,1.000000,1.000000,1.000000,0.000000,0.0,2.000000,132.000000,0.000000,0.000000,0.000000,0.000000,133.000000
75%,2024-08-15 09:18:45,91.000000,0.000000,117.000000,3.000000,3.000000,149.000000,245.000000,0.0,522.000000,194.000000,0.000000,0.000000,0.000000,0.000000,197.000000
max,2025-06-16 23:45:00,100.000000,2195.000000,2400.000000,2180.000000,3863.000000,1125.000000,1721.000000,0.0,2361.000000,2520.000000,2775.000000,2698.000000,2758.000000,2775.000000,3863.000000
std,NaN,35.676437,224.136751,148.560688,389.271960,169.318142,188.830633,375.524054,0.0,506.766364,113.527484,268.126110,159.340922,201.275927,268.126110,272.762503

### Weather

In [36]:
missing_report(weather)

                          Missing Values  Percentage
time                                   0         0.0
temperature_2m (°C)                    0         0.0
cloud_cover (%)                        0         0.0
wind_speed_10m (km/h)                  0         0.0
precipitation (mm)                     0         0.0
weather_code (wmo code)                0         0.0
relative_humidity_2m (%)               0         0.0
pressure_msl (hPa)                     0         0.0
cloud_cover_low (%)                    0         0.0
cloud_cover_mid (%)                    0         0.0
cloud_cover_high (%)                   0         0.0
wind_gusts_10m (km/h)                  0         0.0

In [37]:
weather.describe()

,time,temperature_2m (°C),cloud_cover (%),wind_speed_10m (km/h),precipitation (mm),weather_code (wmo code),relative_humidity_2m (%),pressure_msl (hPa),cloud_cover_low (%),cloud_cover_mid (%),cloud_cover_high (%),wind_gusts_10m (km/h)
count,50520,50520.000000,50520.000000,50520.000000,50520.000000,50520.000000,50520.000000,50520.000000,50520.000000,50520.000000,50520.000000,50520.000000
mean,2022-11-18 11:30:00.000000256,10.823810,65.454691,11.431617,0.083882,11.593448,72.237292,1016.601669,29.909956,34.619220,41.202613,22.985903
min,2020-01-01 00:00:00,-18.400000,0.000000,0.000000,0.000000,0.000000,17.000000,980.500000,0.000000,0.000000,0.000000,1.100000
25%,2021-06-10 05:45:00,4.500000,26.000000,6.800000,0.000000,1.000000,61.000000,1011.100000,0.000000,0.000000,0.000000,13.300000
50%,2022-11-18 11:30:00,10.500000,89.000000,10.100000,0.000000,3.000000,75.000000,1016.900000,7.000000,15.000000,17.000000,20.500000
75%,2024-04-27 17:15:00,16.800000,100.000000,14.800000,0.000000,3.000000,85.000000,1022.500000,58.000000,74.000000,96.000000,29.900000
max,2025-10-05 23:00:00,36.900000,100.000000,51.400000,14.000000,75.000000,100.000000,1047.600000,100.000000,100.000000,100.000000,97.900000
std,NaN,8.062071,39.276774,6.449521,0.343982,20.924026,16.315206,9.153113,38.763580,39.211891,43.809615,12.402464

In [38]:
weather['time'] = pd.to_datetime(weather['time'])
weather.set_index('time', inplace=True)

new_index = pd.date_range(weather.index.min(), weather.index.max(), freq='15T')
weather_15min = weather.reindex(new_index)

num_cols = [
    'temperature_2m (°C)', 'cloud_cover (%)', 'wind_speed_10m (km/h)',
    'precipitation (mm)', 'relative_humidity_2m (%)', 'pressure_msl (hPa)',
    'cloud_cover_low (%)', 'cloud_cover_mid (%)', 'cloud_cover_high (%)',
    'wind_gusts_10m (km/h)'
]
weather_15min[num_cols] = weather_15min[num_cols].interpolate(method='time')

# Kategorische Spalte forward fill
weather_15min['weather_code (wmo code)'] = weather_15min['weather_code (wmo code)'].ffill()

# Optional: Index wieder zur Spalte machen
weather_15min.reset_index(inplace=True)
weather_15min.rename(columns={'index':'time'}, inplace=True)

print(weather_15min.head(5))

                 time  temperature_2m (°C)  cloud_cover (%)  \
0 2020-01-01 00:00:00                  3.4           100.00
1 2020-01-01 00:15:00                  3.4            95.25
2 2020-01-01 00:30:00                  3.4            90.50
3 2020-01-01 00:45:00                  3.4            85.75
4 2020-01-01 01:00:00                  3.4            81.00

   wind_speed_10m (km/h)  precipitation (mm)  weather_code (wmo code)  \
0                   14.5                 0.0                      3.0
1                   14.2                 0.0                      3.0
2                   13.9                 0.0                      3.0
3                   13.6                 0.0                      3.0
4                   13.3                 0.0                      3.0

   relative_humidity_2m (%)  pressure_msl (hPa)  cloud_cover_low (%)  \
0                      87.0             1035.10               100.00
1                      87.0             1035.15                95.25
2                      87.0             1035.20                90.50
3                      87.0             1035.25                85.75
4                      87.0             1035.30                81.00

   cloud_cover_mid (%)  cloud_cover_high (%)  wind_gusts_10m (km/h)
0                  0.0                   0.0                 27.400
1                  0.0                   0.0                 27.025
2                  0.0                   0.0                 26.650
3                  0.0                   0.0                 26.275
4                  0.0                   0.0                 25.900

/var/folders/0q/trpx35nn6hq8qv850qgq5csm0000gn/T/ipykernel_67111/238609643.py:4: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  new_index = pd.date_range(weather.index.min(), weather.index.max(), freq='15T')

In [39]:
missing_report(weather_15min)

                          Missing Values  Percentage
time                                   0         0.0
temperature_2m (°C)                    0         0.0
cloud_cover (%)                        0         0.0
wind_speed_10m (km/h)                  0         0.0
precipitation (mm)                     0         0.0
weather_code (wmo code)                0         0.0
relative_humidity_2m (%)               0         0.0
pressure_msl (hPa)                     0         0.0
cloud_cover_low (%)                    0         0.0
cloud_cover_mid (%)                    0         0.0
cloud_cover_high (%)                   0         0.0
wind_gusts_10m (km/h)                  0         0.0